# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    - id: flake8
      types: [ python ]
      exclude: 'setup.py'
      additional_dependencies: [
          'flake8-blind-except',
          'flake8-commas',
          'flake8-comprehensions',
          'flake8-deprecated',
          'flake8-docstrings',
          'flake8-meiqia',
          'flake8-mutable',
          'flake8-pep3101',
          'flake8-quotes',
          'flake8-string-format',
          'flake8-tidy-imports',
      ]
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

-   repo: https://github.com/timothycrosley/isort
    rev: main
    hooks:
      - id: isort

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy

-   repo: https://github.com/myint/docformatter
    rev: master
    hooks:
    - id: docformatter

-   repo: local
    hooks:
      - id: pytest-bad_jokes
        stages: [push, post-merge]
        name: pytest-bad_jokes
        entry: pytest -v
        language: system
        pass_filenames: false
        always_run: true
